// === Trunk BG 4a - Curved Lean ===
// Theme: trunk that leans/curves to one side, desaturated for depth
//
// Same silhouette as trunk-bg-4b, bark recolored to the muted q/Q/p
// set for the back-of-scene look.
// Stretched to 110 rows tall — the curve resolves to a fully left-leaning
// trunk within the first 7 rows, then plain left-leaning bark repeats down
// to the floor. Clears the floor of half the terrarium's max height (the
// tank's floor-to-lid run is ~152 rows at SCALE 4, so the floor here is
// ~76 rows).
// Size: 8x110 (grid units; multiply by render scale)
// Uses the shared TERRARIUM_PALETTE from palette/terrarium-palette.js.

const TREE_TRUNK_BG_4A = {
  name: 'Trunk BG 4a - Curved Lean',
  theme: 'trunk that leans/curves to one side, desaturated for depth',
  behavior: {
    type: "static",
    layer: "background",
    collision: false,
    placement: "floor",
    animated: false
  },
  width: 8,
  height: 110,
  rows: [
    '....qqqq',
    '...qQqqQ',
    '..qQqqQq',
    '..qQqqQq',
    '.qQqqQq.',
    '.qQqqQq.',
    '.qQppQq.',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQqqQq..',
    'qQppQq..',
    'qQqqQq..',
    'qqQqqQq.',
    'qqQqqQq.',
    'kkkkkkkk',
  ],
};

if (typeof module !== 'undefined' && module.exports) module.exports = TREE_TRUNK_BG_4A;